#!/usr/bin/env python3
"""Prove that `docstamp.py --staged` makes a committed stamp describe its committed
content BY CONSTRUCTION -- and prove the audit beside it still refuses when it does not.

Run from `stamp-docs` -- this skill's own folder in the `claude-skills` repository.
No placeholders:

    python scripts/prove_staged.py

WHY THIS EXISTS (buses-data OA-397, R4 of the process review of 2026-09-17). Until
2026-09-18 the stamp was written by a Stop hook after the turn, so a commit made
mid-turn carried the new content and the old stamp, and a whole apparatus grew around
that gap: a pre-commit AUDIT that refused such a commit, a re-stamp instruction in
CLAUDE.md, a hookify rule, a `--root` flag, and a CI step -- ninety-six commits about
the stamp in a month. `--staged` closes the gap at the only place it can be closed:
inside the pre-commit hook, between the index being built and the commit being
written. This harness drives the real thing -- a throwaway repository, a real
pre-commit hook that calls `--staged` and then the audit, real commits -- and asks
of each commit's TREE, not its working directory, whether the stamp in the committed
blob describes the committed body.

THE MUTATION ARM IS THE POINT. Case 7 runs the identical mid-turn edit through a hook
that does NOT stamp, and requires the audit to refuse it. Without that, "the audit
never fires now" and "the audit is broken" would look the same, and the second is the
one that lets a stale stamp back into main.

Every case builds its own repository and its own policy file naming that repository
as a root, so nothing here reads or writes the real roots. Exits non-zero and names
the case that failed.
"""

import json
import os
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
DOCSTAMP = HERE / "docstamp.py"
AUDIT = HERE / "check_committed_stamps.py"
sys.path.insert(0, str(HERE))
import docstamp as ds  # noqa: E402

failures = []
ran = 0


def check(label, ok, detail=""):
    global ran
    ran += 1
    if not ok:
        failures.append(label)
    print("  {} {}{}".format("ok  " if ok else "FAIL", label, "" if ok or not detail else " -- " + detail))


def run(cmd, cwd, env=None, input_text=None):
    e = dict(os.environ)
    if env:
        e.update(env)
    return subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, env=e, input=input_text)


def git(repo, *args, env=None):
    r = run(["git", *args], repo, env=env)
    return r


def scratch_repo(name, stamp=True):
    """A repository the policy names as a root, with a pre-commit hook that stamps
    (or, for the mutation arm, one that only audits)."""
    root = pathlib.Path(tempfile.mkdtemp(prefix="prove-staged-{}-".format(name)))
    git(root, "init", "-q", "-b", "main")
    git(root, "config", "user.email", "harness@example.invalid")
    git(root, "config", "user.name", "harness")
    git(root, "config", "commit.gpgsign", "false")
    policy = {
        "policyVersion": 1, "shaLen": 8,
        "generatedMarker": "<!-- generated by ",
        "baselineExcludeDirNames": [".git", "node_modules"],
        "roots": [{
            "name": "scratch", "path": str(root).replace("\\", "/"),
            "checkoutDirNames": [root.name], "extensions": [".md"],
            "excludeDirNames": ["_archive"], "excludeDirPatterns": [], "excludeGlobs": ["loop/runs/*"],
        }],
        "pptx": {"fontSizePt": 9, "positionPreference": ["top-right"], "colourOnDark": "B0B7BE", "colourOnLight": "6B6B6B"},
    }
    pol = root / "policy.json"
    pol.write_text(json.dumps(policy, indent=1), encoding="utf-8")
    hooks = root / ".githooks"
    hooks.mkdir()
    py = sys.executable.replace("\\", "/")
    lines = ["#!/bin/sh", "set -e"]
    if stamp:
        lines.append('"{}" "{}" --staged --policy "{}" --quiet'.format(py, str(DOCSTAMP).replace("\\", "/"), str(pol).replace("\\", "/")))
    lines.append('"{}" "{}" --staged || {{ echo "pre-commit: refused -- a staged stamp does not describe its content"; exit 1; }}'.format(py, str(AUDIT).replace("\\", "/")))
    hook = hooks / "pre-commit"
    hook.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    os.chmod(hook, 0o755)
    # THE POST-COMMIT HALF, and why there is one. For a PATHSPEC commit git snapshots
    # the working tree into the real index BEFORE the pre-commit hook runs, commits
    # from a temporary index the hook may change, and writes that early snapshot as
    # the real index afterwards -- so a document the hook stamped reads `MM` in
    # `git status` until something re-adds it, which a loop that refuses a dirty tree
    # would read as work in progress. Resetting the committed documents' index
    # entries to HEAD, and only the index, makes the tree read the truth: clean when
    # the disk copy was stamped too, modified when the author's disk copy differs.
    post = hooks / "post-commit"
    post.write_text("#!/bin/sh\n"
                    "git diff-tree --root --no-commit-id --name-only -r HEAD -- '*.md' '*.pptx' | while IFS= read -r p; do\n"
                    "  [ -n \"$p\" ] && git reset -q -- \"$p\"\n"
                    "done\nexit 0\n", encoding="utf-8", newline="\n")
    os.chmod(post, 0o755)
    git(root, "config", "core.hooksPath", ".githooks")
    return root, pol


def committed(repo, rel):
    """The blob of `rel` in HEAD, decoded, and the audit's view of it."""
    blob = subprocess.run(["git", "-C", str(repo), "show", "HEAD:" + rel], capture_output=True).stdout
    text = blob.decode("utf-8-sig")
    stripped, existing = ds.md_strip_stamp(text.split("\n"))
    actual = ds.md_body_hash(stripped, 8)
    return text, existing, actual


def write(repo, rel, text):
    p = repo / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8", newline="\n")


def modified(repo):
    """Tracked files that differ from the index or HEAD -- the scratch repository's own
    untracked hook and policy file are not the question."""
    lines = git(repo, "status", "--porcelain").stdout.splitlines()
    return [ln for ln in lines if ln and not ln.startswith("??")]


DOC = "# A document\n\nFirst body.\n"

print("\n1. A NEW document committed with a pathspec lands at v1.0 with a stamp that describes its committed body")
repo, pol = scratch_repo("new")
write(repo, "docs/a.md", DOC)
git(repo, "add", "docs/a.md")
c = git(repo, "commit", "-q", "-m", "new doc", "--", "docs/a.md")
check("the commit landed through the hook", c.returncode == 0, (c.stdout + c.stderr)[-300:])
text, existing, actual = committed(repo, "docs/a.md")
check("HEAD's blob carries a stamp", existing is not None)
check("v1.0", existing is not None and (existing["major"], existing["minor"]) == (1, 0), str(existing))
check("and its sha describes the committed body", existing is not None and existing["sha"] == actual, "{} vs {}".format(existing and existing["sha"], actual))
check("the working tree agrees with HEAD (tree+index path)", modified(repo) == [], str(modified(repo)))

print("\n2. THE CASE THE ACTION IS ABOUT: an edit made and committed mid-turn, with no re-stamp step, is current in HEAD and bumped")
write(repo, "docs/a.md", (repo / "docs/a.md").read_text(encoding="utf-8").replace("First body.", "Second body, edited and committed in the same breath."))
git(repo, "add", "docs/a.md")
c = git(repo, "commit", "-q", "-m", "mid-turn edit", "--", "docs/a.md")
check("the commit landed", c.returncode == 0, (c.stdout + c.stderr)[-300:])
text, existing, actual = committed(repo, "docs/a.md")
check("v1.1 -- the minor moved with the content", existing is not None and (existing["major"], existing["minor"]) == (1, 1), str(existing))
check("HEAD's stamp describes HEAD's body", existing is not None and existing["sha"] == actual)
check("the visible line moved too", "**v1.1**" in text)
check("nothing left modified on disk", modified(repo) == [], str(modified(repo)))

print("\n3. An UNCHANGED document re-committed is not bumped (the hash gate holds at commit time too)")
write(repo, "docs/b.md", "# Another\n\nBody.\n")
git(repo, "add", "docs/b.md")
git(repo, "commit", "-q", "-m", "b", "--", "docs/b.md")
before = committed(repo, "docs/b.md")[1]
git(repo, "add", "docs/a.md", "docs/b.md")
c = git(repo, "commit", "-q", "--allow-empty", "-m", "nothing changed", "--", "docs/a.md", "docs/b.md")
after = committed(repo, "docs/b.md")[1]
check("v1.0 stays v1.0", before == after, "{} -> {}".format(before, after))

print("\n4. A PARTIAL stage: the INDEX blob is stamped and the disk copy is left as the author has it")
write(repo, "docs/a.md", (repo / "docs/a.md").read_text(encoding="utf-8").replace("Second body", "Third body"))
git(repo, "add", "docs/a.md")
disk_after_add = (repo / "docs/a.md").read_text(encoding="utf-8")
write(repo, "docs/a.md", disk_after_add + "\nAn unstaged afterthought.\n")   # the disk now differs from the index
c = git(repo, "commit", "-q", "-m", "partial")                                # a plain commit of the index
check("the commit landed", c.returncode == 0, (c.stdout + c.stderr)[-300:])
text, existing, actual = committed(repo, "docs/a.md")
check("HEAD's stamp describes HEAD's body (the staged one)", existing is not None and existing["sha"] == actual)
check("v1.2", existing is not None and (existing["major"], existing["minor"]) == (1, 2), str(existing))
disk_now = (repo / "docs/a.md").read_text(encoding="utf-8")
check("the disk copy still ends with the unstaged afterthought", disk_now.rstrip().endswith("An unstaged afterthought."))
check("and the disk copy's stamp was NOT rewritten (it still says v1.1)", "**v1.1**" in disk_now, disk_now[:200])
check("so the file reads as modified, which is the truth", any("docs/a.md" in ln for ln in modified(repo)), str(modified(repo)))

print("\n5. Scope is the policy's: an excluded folder, an excluded glob and a generated document are left alone")
write(repo, "_archive/old.md", "# Old\n\nArchived.\n")
write(repo, "loop/runs/r1.md", "# Run\n\nA run file.\n")
write(repo, "docs/gen.md", "<!-- generated by a script -->\n# Generated\n\nBody.\n")
git(repo, "add", "_archive/old.md", "loop/runs/r1.md", "docs/gen.md")
c = git(repo, "commit", "-q", "-m", "out of scope", "--", "_archive/old.md", "loop/runs/r1.md", "docs/gen.md")
check("the commit landed", c.returncode == 0, (c.stdout + c.stderr)[-300:])
for rel in ("_archive/old.md", "loop/runs/r1.md", "docs/gen.md"):
    check("{} carries no stamp".format(rel), committed(repo, rel)[1] is None)

print("\n6. A repository the policy does not name is a no-op that says so, exit 0")
other = pathlib.Path(tempfile.mkdtemp(prefix="prove-staged-unnamed-"))
git(other, "init", "-q", "-b", "main")
write(other, "x.md", "# X\n")
git(other, "add", "x.md")
r = run([sys.executable, str(DOCSTAMP), "--staged", "--policy", str(pol)], other)
check("exit 0", r.returncode == 0, r.stdout + r.stderr)
check("and it says the repository is not a named root", "not a root the stamp policy names" in r.stdout, r.stdout)
check("x.md is still unstamped in the index", "docstamp" not in run(["git", "show", ":x.md"], other).stdout)

print("\n7. THE MUTATION ARM: the same mid-turn edit through a hook that does not stamp is REFUSED by the audit")
repo2, pol2 = scratch_repo("nostamp", stamp=False)
stamped_doc = ds.stamp_markdown_text(DOC, 8, ds.dt.date(2026, 9, 1))[3]
write(repo2, "docs/a.md", stamped_doc)
git(repo2, "add", "docs/a.md")
c = git(repo2, "commit", "-q", "-m", "seed (current stamp)", "--", "docs/a.md")
check("a correctly stamped seed lands through the audit-only hook", c.returncode == 0, (c.stdout + c.stderr)[-300:])
write(repo2, "docs/a.md", stamped_doc.replace("First body.", "Edited without a re-stamp."))
git(repo2, "add", "docs/a.md")
c = git(repo2, "commit", "-q", "-m", "stale", "--", "docs/a.md")
check("the stale commit is REFUSED", c.returncode != 0 and git(repo2, "rev-list", "--count", "HEAD").stdout.strip() == "1", "exit {}; commits={}".format(c.returncode, git(repo2, "rev-list", "--count", "HEAD").stdout.strip()))
check("and the refusal names the audit", "refused" in (c.stdout + c.stderr), (c.stdout + c.stderr)[-300:])
# The control for the arm: run --staged by hand on the same index, then commit through
# the audit-only hook. The audit passing here is what shows it refused above for the
# stamp and not for something else about the fixture.
r = run([sys.executable, str(DOCSTAMP), "--staged", "--policy", str(pol2), "--quiet"], repo2)
c = git(repo2, "commit", "-q", "-m", "stamped by hand, then audited", "--", "docs/a.md")
check("the same edit lands once --staged has run, through the audit-only hook", c.returncode == 0, (c.stdout + c.stderr)[-300:])
text, existing, actual = committed(repo2, "docs/a.md")
check("and HEAD's stamp describes HEAD's body", existing is not None and existing["sha"] == actual)

print("\n8. --dry-run stamps nothing and says so")
write(repo, "docs/c.md", "# C\n\nBody.\n")
git(repo, "add", "docs/c.md")
r = run([sys.executable, str(DOCSTAMP), "--staged", "--policy", str(pol), "--dry-run"], repo)
check("exit 0 and 'dry run' in the summary", r.returncode == 0 and "dry run" in r.stdout, r.stdout + r.stderr)
check("the index blob is untouched", "docstamp" not in run(["git", "show", ":docs/c.md"], repo).stdout)

print()
if failures:
    print("FAILED -- {} of {} assertions did not hold: {}".format(len(failures), ran, "; ".join(failures)))
    sys.exit(1)
print("OK -- all {} assertions held: a document committed mid-turn carries a stamp that describes its committed body, a partial stage stamps the index and leaves the disk alone, scope is the policy's, an unnamed repository is a no-op, and the audit still refuses a stale stamp when nothing stamps.".format(ran))
